### ISSUE TITLE
Add Kong 3.4 and 3.5 to test matrix

### ISSUE THREAD

**Issue by rainest** [Kong/go-database-reconciler#15]
Kong 3.4 and 3.5 are currently absent from the test matrix. They will require some change to test expectations to address a difference in their normal defaults: https://github.com/Kong/go-database-reconciler/actions/runs/6946338428/job/18897697301

**Comment by pmalek** [comment]
Already in the test matrix: 

- https://github.com/Kong/go-database-reconciler/blob/c70e4ecf881c99043fee22cf08d23b03643659d3/.github/workflows/integration.yaml#L11-L29
- https://github.com/Kong/go-database-reconciler/blob/c70e4ecf881c99043fee22cf08d23b03643659d3/.github/workflows/integration-enterprise.yaml#L11-L27
